version: '3.4'

services:
  postgres_img_account:
      image: postgres
      restart: always
      environment:
        "POSTGRES_USER": "vlad1234"
        "POSTGRES_PASSWORD": "vlad1234"
        "POSTGRES_DB": "accountdb"
      volumes:
        - postgres-data:/var/lib/postgresql/data
  accountservice:
    image: ${DOCKER_REGISTRY-}accountservice
    build:
      context: .
      dockerfile: AccountService/Dockerfile
  articleservice:
    image: ${DOCKER_REGISTRY-}articleservice
    build:
      context: .
      dockerfile: ArticleService/Dockerfile
    depends_on:
     - postgres_img_account

  
  
volumes:
  postgres-data:

