version: '3.4'


networks:
  backend:
    driver: bridge

services:


    chatservice:
        image: ${DOCKER_REGISTRY-}chatservice
        build:
            context: .
            dockerfile: ChatService/Dockerfile



    ocelotgateway:
        image: ${DOCKER_REGISTRY-}ocelotgateway
   
        build:
            context: .
            dockerfile: OcelotGateway/Dockerfile



    articleservice:
        image: ${DOCKER_REGISTRY-}articleservice

        build:
          context: .
          dockerfile: ArticleService/Dockerfile
          

    accountservice:
        image: ${DOCKER_REGISTRY-}accountservice
        build:
            context: .
            dockerfile: AccountService/Dockerfile
        
    account_db:
        image: postgres
        restart: always
      
    article_db:
        image: postgres
        restart: always

    
volumes:
    article_data:
    account_data:

