version: '3.4'

services:
  accountservice:
    image: ${DOCKER_REGISTRY-}accountservice
    build:
      context: .
      dockerfile: AccountService/Dockerfile
  articleservice:
    image: ${DOCKER_REGISTRY-}articleservice
    build:
      context: .
      dockerfile: ArticleService/Dockerfile

  postgres_img_account:
    image: postgres:lates
    ports: 
      - "5432"
    restart: always
    environment:
      "POSTGRES_USER": "vlad1234"
      "POSTGRES_PASSWORD": "vlad1234"
      "POSTGRES_DB": "accountdb"

