version: '3.4'


services:


    chatservice:
        container_name: chatservice
        ports:
            - "8090:80"





    ocelotgateway:
        container_name: ocelot_gateway
   
        ports:
            - "8091:80"

        depends_on:
            - articleservice
            - accountservice
            - chatservice

        environment:
            - ASPNETCORE_URLS=http://+:80 



    articleservice:
        container_name: articleservice
        depends_on:
         - article_db
        ports:
            - "8088:80"
        environment:
            - ConnectionStrings__DefaultConnection=Server=article_db;Port=5432;Database=articledb;User Id=postgres;Password=postgres;



    accountservice:
        container_name:  accountservice
        depends_on:
            - account_db
        ports:
            - "8809:80"
 
        environment:
            - ConnectionStrings__DefaultConnection=Server=account_db;Port=5432;Database=accountdb;User Id=postgres;Password=postgres;


    account_db:
    
        container_name: account_db
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=accountdb
    
        ports:
            - "5433:5432"
        expose:
            - "5433"
        volumes:
            - account_data:/var/lib/postgresql/data


    article_db:
        container_name: article_db
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=articledb
        ports:
            - "5432:5432"
        volumes:
            - article_data:/var/lib/postgresql/data
    